source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '14.0'
use_frameworks!

target 'NibDesignableDemo' do
  pod 'NibDesignable', :path => '../'

  target 'NibDesignableDemoTests' do
    inherit! :search_paths
  end
end
